variables:
  DEVRWDWEBWAx401: '20230216.4'
  DEVRWDWEBWAx402: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx403: 'releases_public-beta-rc2.8-rpd-20231107.1'
  DEVRWDWEBWAx404: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx405: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx406: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx407: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx408: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx409: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx410: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx411: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx412: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx413: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBWAx414: 'releases_public-beta-rc2.8-rpd-20231106.2'
  DEVRWDWEBWAx415: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBFAx401: 'releases_public-beta-rc2.8-rpd-20231107.1'
  DEVRWDWEBFAx402: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBFAx403: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBFAx404: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBFAx405: 'releases_public-beta-rc2.9-rpd'
  DEVRWDWEBFAx406: 'releases_public-beta-rc2.8-rpd-20231108.3'
  DEVRWDWEBFAx407: 'releases_public-beta-rc2.9-rpd'