trigger: none
pr: none
pool: DEFRA-COMMON-ubuntu2004-SSV3

parameters:
- name: dev1
  displayName: 'DEV1'
  default: false
  type: boolean
- name: dev2
  displayName: 'DEV2'
  default: false
  type: boolean
- name: dev3
  displayName: 'DEV3'
  default: false
  type: boolean
- name: dev4
  displayName: 'DEV4'
  default: false
  type: boolean
- name: dev5
  displayName: 'DEV5'
  default: false
  type: boolean
- name: dev6
  displayName: 'DEV6'
  default: false
  type: boolean
- name: dev7
  displayName: 'DEV7'
  default: false
  type: boolean
- name: dev8
  displayName: 'DEV8'
  default: false
  type: boolean
- name: dev9
  displayName: 'DEV9'
  default: true
  type: boolean
- name: tst1
  displayName: 'TST1'
  default: false
  type: boolean

jobs:
- job: EntryJob
  steps:
  - script: echo "This is the entry job"

- ${{ each parameter in parameters }}:
  - ${{ if eq(parameter.Value, true) }}:
    - job: RunningTemplate
      displayName: 'Run template to create strorage containers'
      variables:
        - template: vars/${{ parameter.Key }}.yaml
      steps:
      - template: templates/storage-account-all-containers.yaml
        parameters:
            azureSubscription: ${{variables['subscriptionName']}}
            resourceGroup: $(webResourceGroupName)
            targetResource: ${{ lower(variables.environmentGroup) }}rwdwebsa${{ variables['environmentSpoke'] }}403
            containerName: pom-upload-container
      - template: templates/storage-account-all-containers.yaml
        parameters:
            azureSubscription: ${{variables['subscriptionName']}}
            resourceGroup: $(webResourceGroupName)
            targetResource: ${{ lower(variables.environmentGroup) }}rwdwebsa${{ variables['environmentSpoke'] }}403
            containerName: registration-upload-container