trigger: none
pr: none

parameters:
- name: teamName
  displayName: 'Select Environment:'
  type: string
  values:
  - DEV1
  - DEV2
  - DEV3
  - DEV4
  - DEV5
  - DEV6
  - DEV7
  - DEV8
  - DEV9
  - DEV10
  - DEV11
  - DEV12
  - DEV13
  - DEV14
  - tst
  - preprod
  - prod
- name: restartApp
  displayName: Restart the applications after config change
  type: boolean
  default: true

variables:
- template: templates/env-specific-config.yaml
  parameters:
    teamName: ${{ parameters.teamName }}
- name: settingsDir
  value: $(Build.SourcesDirectory)/${{ lower(variables.environmentName) }}
- ${{ if and( ne(parameters.teamName, 'tst'), ne(parameters.teamName, 'preprod'), ne(parameters.teamName, 'prod'), ne(parameters.teamName, 'DEV8')) }}:
  - name: useDevConfig
    value: true
  - name: configDir
    value: $(Pipeline.Workspace)/s/dev/config
- ${{ else }}:
  - name: useDevConfig
    value: false
  - name: configDir
    value: $(settingsDir)

pool: $(agentPool)

jobs:

- template: templates/mass-configuration-template.yaml
  parameters:
    restartApp: ${{ parameters.restartApp }}
    subscriptionName: ${{ variables.subscriptionName }}
    webResourceGroupName: ${{ variables.webResourceGroupName }}
    useDevConfig: ${{ variables.useDevConfig }}
    configDirectory: ${{ variables.configDir }}
    environmentSpoke: $(environmentSpoke)
    environmentGroup: ${{ variables.environmentGroup }}
    configTemplateInputDirectory: $(Pipeline.Workspace)/s/dev
