trigger: none
pr: none

parameters:
- name: teamName
  displayName: 'Select Environment:'
  type: string
  values:
  - DEV1
  - DEV2
  - DEV3
  - DEV4
  - DEV5
  - DEV6
  - DEV7
  - DEV8
  - DEV9
  - DEV10
  - DEV11
  - TST1
  - PRE1

variables:
- ${{ if eq(parameters.teamName, 'DEV1') }}:
  - template: vars/dev1.yaml
- ${{ elseif eq(parameters.teamName, 'DEV2') }}:
  - template: vars/dev2.yaml
- ${{ elseif eq(parameters.teamName, 'DEV3') }}:
  - template: vars/dev3.yaml
- ${{ elseif eq(parameters.teamName, 'DEV4') }}:
  - template: vars/dev4.yaml
- ${{ elseif eq(parameters.teamName, 'DEV5') }}:
  - template: vars/dev5.yaml
- ${{ elseif eq(parameters.teamName, 'DEV6') }}:
  - template: vars/dev6.yaml
- ${{ elseif eq(parameters.teamName, 'DEV7') }}:
  - template: vars/dev7.yaml
- ${{ elseif eq(parameters.teamName, 'DEV8') }}:
  - template: vars/dev8.yaml
- ${{ elseif eq(parameters.teamName, 'DEV10') }}:
  - template: vars/dev10.yaml
- ${{ elseif eq(parameters.teamName, 'DEV11') }}:
  - template: vars/dev11.yaml 
- ${{ elseif eq(parameters.teamName, 'TST1') }}:
  - template: vars/tst1.yaml
- ${{ elseif eq(parameters.teamName, 'PRE1') }}:
  - template: vars/pre1.yaml
- ${{ elseif eq(parameters.teamName, 'PRD1') }}:
  - template: vars/prd1.yaml
- ${{ else }}:
  - template: vars/dev9.yaml

- name: settingsDir
  value: $(Build.SourcesDirectory)/${{ lower(variables.environmentName) }}

pool: $(agentPool)

jobs:
- job: GetSettings
  displayName: Getting settings for ${{ variables.subscriptionName }}
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ variables.subscriptionName }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd $(settingsDir)
        for filename in `ls *RWDWEBFA*`
        do
          service=`basename -s .json $filename`
          echo "AppSettings for " $service
          az functionapp config show --subscription ${{ variables.subscriptionName }} -g ${{ variables.webResourceGroupName }} -n $service | grep -i linuxFxVersion
          echo -e "\n"
        done
        for filename in `ls *RWDWEBWA*`
        do
          service=`basename -s .json $filename`
          echo "AppSettings for " $service
          az webapp config show --subscription ${{ variables.subscriptionName }} -g ${{ variables.webResourceGroupName }} -n $service | grep -i linuxFxVersion
          echo -e "\n"
        done
    displayName: "Get settings"
